<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="5234" started-at="2018-06-03T06:08:19Z" finished-at="2018-06-03T06:08:24Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="5234" started-at="2018-06-03T06:08:19Z" finished-at="2018-06-03T06:08:24Z">
      <class name="com.qa.test.HomePage_PreloginTest">
        <test-method status="PASS" signature="initializationNew()[pri:0, instance:com.qa.test.HomePage_PreloginTest@42607a4f]" name="initializationNew" is-config="true" duration-ms="16692" started-at="2018-06-03T11:38:02Z" finished-at="2018-06-03T11:38:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializationNew -->
        <test-method status="PASS" signature="HomePage_Prelogin1()[pri:1, instance:com.qa.test.HomePage_PreloginTest@42607a4f]" name="HomePage_Prelogin1" duration-ms="25" started-at="2018-06-03T11:38:19Z" finished-at="2018-06-03T11:38:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HomePage_Prelogin1 -->
        <test-method status="PASS" signature="homePage_LogoDisplayed()[pri:2, instance:com.qa.test.HomePage_PreloginTest@42607a4f]" name="homePage_LogoDisplayed" duration-ms="78" started-at="2018-06-03T11:38:24Z" finished-at="2018-06-03T11:38:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePage_LogoDisplayed -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.test.HomePage_PreloginTest@42607a4f]" name="tearDown" is-config="true" duration-ms="673" started-at="2018-06-03T11:38:24Z" finished-at="2018-06-03T11:38:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.test.HomePage_PreloginTest -->
      <class name="com.qa.test.RegistrationTest">
        <test-method status="FAIL" signature="verify_url_RegistrationPage()[pri:1, instance:com.qa.test.RegistrationTest@782663d3]" name="verify_url_RegistrationPage" duration-ms="5025" started-at="2018-06-03T11:38:19Z" finished-at="2018-06-03T11:38:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.home24.de/] but found [https://www.home24.de/meinkundenkonto/kunde/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.home24.de/] but found [https://www.home24.de/meinkundenkonto/kunde/login]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.qa.test.RegistrationTest.verify_url_RegistrationPage(RegistrationTest.java:45)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_url_RegistrationPage -->
      </class> <!-- com.qa.test.RegistrationTest -->
      <class name="com.qa.test.HomePage_PostLoginTest">
        <test-method status="FAIL" signature="verify_url_HomePagePostlogin()[pri:1, instance:com.qa.test.HomePage_PostLoginTest@1990a65e]" name="verify_url_HomePagePostlogin" duration-ms="4" started-at="2018-06-03T11:38:24Z" finished-at="2018-06-03T11:38:24Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerExceptionat com.qa.test.HomePage_PostLoginTest.verify_url_HomePagePostlogin(HomePage_PostLoginTest.java:25)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_url_HomePagePostlogin -->
      </class> <!-- com.qa.test.HomePage_PostLoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
